name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.2.0'
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test
      env:
        CI: true
